version: '3.8'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    develop:
      watch:
        - path: web/requirements.txt
          action: rebuild
        - path: movierater/
          target: /code/movierater
          action: sync
