# Generated by Django 5.0.6 on 2024-08-06 21:08

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_film_imdb_rating_film_premiera_film_rok'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.IntegerField()),
                ('rodzaj', models.IntegerField(choices=[(4, 'Komedia'), (0, 'Nieznane'), (2, 'Sci-fi'), (3, 'Drama'), (1, 'Horror')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='extra_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.expressions.Case, to='api.extrainfo'),
        ),
    ]
