# Generated by Django 5.0.6 on 2024-08-13 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_extrainfo_rodzaj_recenzja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrainfo',
            name='rodzaj',
            field=models.IntegerField(choices=[(2, 'Sci-fi'), (3, 'Drama'), (0, 'Nieznane'), (4, 'Komedia'), (1, 'Horror')], default=0),
        ),
        migrations.AlterField(
            model_name='recenzja',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenzje', to='api.film'),
        ),
        migrations.CreateModel(
            name='Aktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=32)),
                ('nazwisko', models.CharField(max_length=32)),
                ('filmy', models.ManyToManyField(to='api.film')),
            ],
        ),
    ]
